# Form implementation generated from reading ui file 'linear_curve_fitting.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LinearCurveFitting(object):
    def setupUi(self, LinearCurveFitting):
        LinearCurveFitting.setObjectName("LinearCurveFitting")
        LinearCurveFitting.resize(600, 500)
        self.widget = QtWidgets.QWidget(parent=LinearCurveFitting)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_x = QtWidgets.QLabel(parent=self.widget)
        self.label_x.setObjectName("label_x")
        self.verticalLayout.addWidget(self.label_x)
        self.x_input = QtWidgets.QLineEdit(parent=self.widget)
        self.x_input.setObjectName("x_input")
        self.verticalLayout.addWidget(self.x_input)
        self.label_y = QtWidgets.QLabel(parent=self.widget)
        self.label_y.setObjectName("label_y")
        self.verticalLayout.addWidget(self.label_y)
        self.y_input = QtWidgets.QLineEdit(parent=self.widget)
        self.y_input.setObjectName("y_input")
        self.verticalLayout.addWidget(self.y_input)
        self.plot_button = QtWidgets.QPushButton(parent=self.widget)
        self.plot_button.setObjectName("plot_button")
        self.verticalLayout.addWidget(self.plot_button)
        self.plot_area = QtWidgets.QLabel(parent=self.widget)
        self.plot_area.setObjectName("plot_area")
        self.verticalLayout.addWidget(self.plot_area)

        self.retranslateUi(LinearCurveFitting)
        QtCore.QMetaObject.connectSlotsByName(LinearCurveFitting)

    def retranslateUi(self, LinearCurveFitting):
        _translate = QtCore.QCoreApplication.translate
        LinearCurveFitting.setWindowTitle(_translate("LinearCurveFitting", "Linear Curve Fitting"))
        self.label_x.setText(_translate("LinearCurveFitting", "Enter X values (comma-separated):"))
        self.label_y.setText(_translate("LinearCurveFitting", "Enter Y values (comma-separated):"))
        self.plot_button.setText(_translate("LinearCurveFitting", "Plot Fit"))
        self.plot_area.setText(_translate("LinearCurveFitting", "Graph will be displayed here"))