# Form implementation generated from reading ui file 'newton_forward_derivative.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewtonForwardDerivative(object):
    def setupUi(self, NewtonForwardDerivative):
        NewtonForwardDerivative.setObjectName("NewtonForwardDerivative")
        NewtonForwardDerivative.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(parent=NewtonForwardDerivative)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_x = QtWidgets.QLabel(parent=self.groupBox)
        self.label_x.setObjectName("label_x")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_x)
        self.lineEdit_x = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_x)
        self.label_y = QtWidgets.QLabel(parent=self.groupBox)
        self.label_y.setObjectName("label_y")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_y)
        self.lineEdit_y = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_y)
        self.verticalLayout.addWidget(self.groupBox)
        self.pushButton_calculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_calculate.setStyleSheet("font-weight: bold; background-color: white; color: black; border: 1px solid black; padding: 5px;")
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.verticalLayout.addWidget(self.pushButton_calculate)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_result_title = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_result_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_result_title.setStyleSheet("font-size: 12px; font-weight: bold; padding-bottom: 5px;")
        self.label_result_title.setObjectName("label_result_title")
        self.verticalLayout_2.addWidget(self.label_result_title)
        self.label_result = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_result.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_result.setStyleSheet("font-size: 14px; color: #2c3e50; background-color: #f1f1f1; padding: 10px; border-radius: 5px;")
        self.label_result.setObjectName("label_result")
        self.verticalLayout_2.addWidget(self.label_result)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(NewtonForwardDerivative)
        QtCore.QMetaObject.connectSlotsByName(NewtonForwardDerivative)

    def retranslateUi(self, NewtonForwardDerivative):
        _translate = QtCore.QCoreApplication.translate
        NewtonForwardDerivative.setWindowTitle(_translate("NewtonForwardDerivative", "First Derivative (Newton’s Forward Difference)"))
        self.groupBox.setTitle(_translate("NewtonForwardDerivative", "Input Parameters"))
        self.label_x.setText(_translate("NewtonForwardDerivative", "x values (comma-separated):"))
        self.lineEdit_x.setPlaceholderText(_translate("NewtonForwardDerivative", "e.g., 0,1,2"))
        self.label_y.setText(_translate("NewtonForwardDerivative", "y values (comma-separated):"))
        self.lineEdit_y.setPlaceholderText(_translate("NewtonForwardDerivative", "e.g., 1,8,27"))
        self.pushButton_calculate.setText(_translate("NewtonForwardDerivative", "Calculate dy/dx at Middle Point"))
        self.label_result_title.setText(_translate("NewtonForwardDerivative", "Result:"))
        self.label_result.setText(_translate("NewtonForwardDerivative", "Result will be displayed here"))
