# Form implementation generated from reading ui file 'trapezoidal_rule.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TrapezoidalRule(object):
    def setupUi(self, TrapezoidalRule):
        TrapezoidalRule.setObjectName("TrapezoidalRule")
        TrapezoidalRule.resize(350, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(TrapezoidalRule)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_task = QtWidgets.QLabel(parent=TrapezoidalRule)
        self.label_task.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_task.setObjectName("label_task")
        self.verticalLayout.addWidget(self.label_task)
        self.label_problem = QtWidgets.QLabel(parent=TrapezoidalRule)
        self.label_problem.setWordWrap(True)
        self.label_problem.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_problem.setObjectName("label_problem")
        self.verticalLayout.addWidget(self.label_problem)
        self.groupBox_input = QtWidgets.QGroupBox(parent=TrapezoidalRule)
        self.groupBox_input.setObjectName("groupBox_input")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_input)
        self.formLayout.setObjectName("formLayout")
        self.label_a = QtWidgets.QLabel(parent=self.groupBox_input)
        self.label_a.setObjectName("label_a")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_a)
        self.lineEdit_a = QtWidgets.QLineEdit(parent=self.groupBox_input)
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_a)
        self.label_b = QtWidgets.QLabel(parent=self.groupBox_input)
        self.label_b.setObjectName("label_b")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_b)
        self.lineEdit_b = QtWidgets.QLineEdit(parent=self.groupBox_input)
        self.lineEdit_b.setObjectName("lineEdit_b")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_b)
        self.label_n = QtWidgets.QLabel(parent=self.groupBox_input)
        self.label_n.setObjectName("label_n")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_n)
        self.lineEdit_n = QtWidgets.QLineEdit(parent=self.groupBox_input)
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_n)
        self.verticalLayout.addWidget(self.groupBox_input)
        self.pushButton_calculate = QtWidgets.QPushButton(parent=TrapezoidalRule)
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.verticalLayout.addWidget(self.pushButton_calculate)
        self.groupBox_result = QtWidgets.QGroupBox(parent=TrapezoidalRule)
        self.groupBox_result.setObjectName("groupBox_result")
        self.verticalLayout_result = QtWidgets.QVBoxLayout(self.groupBox_result)
        self.verticalLayout_result.setSpacing(10)
        self.verticalLayout_result.setObjectName("verticalLayout_result")
        self.label_result = QtWidgets.QLabel(parent=self.groupBox_result)
        self.label_result.setWordWrap(True)
        self.label_result.setMinimumSize(QtCore.QSize(0, 60))
        self.label_result.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_result.setObjectName("label_result")
        self.verticalLayout_result.addWidget(self.label_result)
        self.verticalLayout.addWidget(self.groupBox_result)

        self.retranslateUi(TrapezoidalRule)
        QtCore.QMetaObject.connectSlotsByName(TrapezoidalRule)

    def retranslateUi(self, TrapezoidalRule):
        _translate = QtCore.QCoreApplication.translate
        TrapezoidalRule.setWindowTitle(_translate("TrapezoidalRule", "Trapezoidal Rule Approximation"))
        self.label_task.setText(_translate("TrapezoidalRule", "Task 8: Trapezoidal Rule"))
        self.label_task.setStyleSheet(_translate("TrapezoidalRule", "font-size: 14px; font-weight: bold; padding-bottom: 5px;"))
        self.label_problem.setText(_translate("TrapezoidalRule", "Problem: Approximate ∫₀¹ (x² + x)dx using the Trapezoidal Rule with 4 subintervals. Compare with the exact value."))
        self.label_problem.setStyleSheet(_translate("TrapezoidalRule", "font-size: 12px; font-weight: bold; padding-bottom: 10px;"))
        self.groupBox_input.setTitle(_translate("TrapezoidalRule", "Input Parameters"))
        self.label_a.setText(_translate("TrapezoidalRule", "Lower limit (a):"))
        self.lineEdit_a.setText(_translate("TrapezoidalRule", "0"))
        self.label_b.setText(_translate("TrapezoidalRule", "Upper limit (b):"))
        self.lineEdit_b.setText(_translate("TrapezoidalRule", "1"))
        self.label_n.setText(_translate("TrapezoidalRule", "Number of subintervals (n):"))
        self.lineEdit_n.setText(_translate("TrapezoidalRule", "4"))
        self.pushButton_calculate.setText(_translate("TrapezoidalRule", "Calculate Integral"))
        self.pushButton_calculate.setStyleSheet(_translate("TrapezoidalRule", "font-weight: bold; background-color: white; color: black; border: 1px solid black; padding: 8px;"))
        self.groupBox_result.setTitle(_translate("TrapezoidalRule", "Result"))
        self.label_result.setText(_translate("TrapezoidalRule", "Result will be displayed here"))
        self.label_result.setStyleSheet(_translate("TrapezoidalRule", "font-size: 14px; color: #2c3e50; background-color: #f1f1f1; padding: 15px; border-radius: 5px; min-height: 60px;"))
